### ISSUE TITLE
Info about the requirements

### ISSUE THREAD

**Issue by Felipefpl** [Lu-Die-Milchkuh/yuzu-will-live#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be nice to explain why opengl 4.6 is required for the emulation. Something that the original yuzu didnt do. Why the older versions of OpenGL/DirectX cant be used?

### Why would this feature be useful?

More info always better.

**Comment by Lu-Die-Milchkuh** [comment]
Hey there. I am not going to maintain the codebase, this was just for preservation reasons. There are a few people in the Yuzu Subreddit that are willing to continue Yuzus Legacy

**Comment by Lu-Die-Milchkuh** [comment]
Here is the Post in question: https://www.reddit.com/r/yuzu/comments/1b6rr5f/introducing_yuzu_vanced/
